// react-form/src/components/form.jsx
import { useState } from 'react';
import Input from './inputs';
import RadioButtons from './radiobuttons';
import Select from './selects';
import './form.css';

const Form = ({ editUser, onCancel, onSuccess }) => {
  const [formData, setFormData] = useState(editUser || {
    dni: '',
    nombres: '',
    apellidos: '',
    fechaNacimiento: '',
    genero: '',
    ciudad: ''
  });

  const [message, setMessage] = useState('');
  const isEditing = !!editUser;

  // Manejar cambios en los inputs
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  // Manejar envío del formulario
  const handleSubmit = async (e) => {
    e.preventDefault();
    
    try {
      const url = isEditing 
        ? `http://localhost:3000/api/usuarios/${editUser.id}`
        : 'http://localhost:3000/api/usuarios';
      
      const method = isEditing ? 'PUT' : 'POST';
      
      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });

      if (response.ok) {
        setMessage(isEditing ? 'Usuario actualizado exitosamente' : 'Usuario creado exitosamente');
        if (!isEditing) {
          setFormData({
            dni: '',
            nombres: '',
            apellidos: '',
            fechaNacimiento: '',
            genero: '',
            ciudad: ''
          });
        }
        // Notificar éxito al componente padre
        if (onSuccess) {
          onSuccess();
        }
      } else {
        const error = await response.json();
        setMessage(error.error || 'Error al procesar usuario');
      }
    } catch (error) {
      setMessage('Error de conexión');
    }
  };

  // Opciones para radio buttons y select
  const generoOptions = [
    { value: 'masculino', label: 'Masculino' },
    { value: 'femenino', label: 'Femenino' },
    { value: 'otro', label: 'Otro' }
  ];

  const ciudadOptions = [
    'Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 
    'Piura', 'Cusco', 'Huancayo', 'Tacna','Milagro','Guayaquil'
  ];

  return (
    <div className="form-container">
      <h2>{isEditing ? 'Editar Usuario' : 'Formulario de Usuario'}</h2>
      
      {message && <div className="message">{message}</div>}

      <form onSubmit={handleSubmit}>
        <Input
          type="text"
          name="dni"
          value={formData.dni}
          onChange={handleChange}
          label="DNI"
          maxLength="10"
          placeholder="CI. Máximo 10 dígitos"
        />

        <Input
          type="text"
          name="nombres"
          value={formData.nombres}
          onChange={handleChange}
          label="Nombres"
          placeholder="Nombres completos"
        />

        <Input
          type="text"
          name="apellidos"
          value={formData.apellidos}
          onChange={handleChange}
          label="Apellidos"
          placeholder="Apellidos completos"
        />

        <Input
          type="date"
          name="fechaNacimiento"
          value={formData.fechaNacimiento}
          onChange={handleChange}
          label="Fecha de Nacimiento"
        />

        <RadioButtons
          name="genero"
          value={formData.genero}
          onChange={handleChange}
          options={generoOptions}
          label="Género"
        />

        <Select
          name="ciudad"
          value={formData.ciudad}
          onChange={handleChange}
          options={ciudadOptions}
          label="Ciudad"
        />

        <button type="submit">
          {isEditing ? 'Actualizar Usuario' : 'Guardar Usuario'}
        </button>
        
        {isEditing && (
          <button type="button" onClick={onCancel} className="cancel-btn">
            Cancelar
          </button>
        )}
      </form>
    </div>
  );
};

export default Form;

// vue-form/src/Form.vue
<template>
  <div class="form-container">
    <h2>{{ isEditing ? 'Editar Usuario' : 'Formulario de Usuario' }}</h2>
    <div v-if="message" class="message">{{ message }}</div>

    <form @submit.prevent="handleSubmit">
      <div class="form-group">
        <label>DNI:</label>
        <input type="text" v-model="formData.dni" maxlength="10" placeholder="CI. Máximo 10 dígitos" @input="validateDNI" required />
      </div>
      
      <div class="form-group">
        <label>Nombres:</label>
        <input type="text" v-model="formData.nombres" placeholder="Nombres completos" required />
      </div>
      
      <div class="form-group">
        <label>Apellidos:</label>
        <input type="text" v-model="formData.apellidos" placeholder="Apellidos completos" required />
      </div>
      
      <div class="form-group">
        <label>Fecha de Nacimiento:</label>
        <input type="date" v-model="formData.fechaNacimiento" required />
      </div>
      
      <div class="form-group">
        <label>Género:</label>
        <div class="radio-group">
          <label><input type="radio" v-model="formData.genero" value="masculino" required /> Masculino</label>
          <label><input type="radio" v-model="formData.genero" value="femenino" required /> Femenino</label>
          <label><input type="radio" v-model="formData.genero" value="otro" required /> Otro</label>
        </div>
      </div>
      
      <div class="form-group">
        <label>Ciudad:</label>
        <select v-model="formData.ciudad" required>
          <option value="">Seleccionar ciudad</option>
          <option v-for="ciudad in ciudades" :key="ciudad" :value="ciudad">{{ ciudad }}</option>
        </select>
      </div>
      
      <button type="submit" :disabled="isSubmitting">
        {{ isSubmitting ? 'Guardando...' : (isEditing ? 'Actualizar Usuario' : 'Guardar Usuario') }}
      </button>
      <button v-if="isEditing" type="button" @click="$emit('cancel')" class="cancel-btn">Cancelar</button>
    </form>
  </div>
</template>

<script>
export default {
  name: 'Form',
  props: { editUser: { type: Object, default: null } },
  emits: ['cancel', 'success'],
  data() {
    return {
      formData: { dni: '', nombres: '', apellidos: '', fechaNacimiento: '', genero: '', ciudad: '' },
      message: '',
      isSubmitting: false,
      ciudades: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Cusco', 'Huancayo', 'Tacna', 'Milagro', 'Guayaquil']
    }
  },
  computed: {
    isEditing() { return !!this.editUser }
  },
  watch: {
    editUser: {
      handler(newUser) {
        if (newUser) {
          this.formData = { ...newUser }
        } else {
          this.resetForm()
        }
      },
      immediate: true
    }
  },
  methods: {
    validateDNI() {
      this.formData.dni = this.formData.dni.replace(/\D/g, '').slice(0, 10)
    },
    resetForm() {
      this.formData = { dni: '', nombres: '', apellidos: '', fechaNacimiento: '', genero: '', ciudad: '' }
      // No limpiar el mensaje inmediatamente, dejarlo que se vea
    },
    async handleSubmit() {
      this.isSubmitting = true
      this.message = ''
      try {
        const url = this.isEditing ? `http://localhost:3000/api/usuarios/${this.editUser.id}` : 'http://localhost:3000/api/usuarios'
        const response = await fetch(url, {
          method: this.isEditing ? 'PUT' : 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(this.formData)
        })
        if (response.ok) {
          this.message = this.isEditing ? 'Usuario actualizado exitosamente' : 'Usuario creado exitosamente'
          
          // Limpiar formulario inmediatamente si no está editando
          if (!this.isEditing) this.resetForm()
          
          // Notificar éxito al padre
          this.$emit('success')
          
          // Limpiar mensaje después de 3 segundos
          setTimeout(() => {
            this.message = ''
          }, 3000)
        } else {
          const error = await response.json()
          this.message = error.error || 'Error al procesar usuario'
        }
      } catch (error) {
        this.message = 'Error de conexión'
      } finally {
        this.isSubmitting = false
      }
    }
  }
}
</script>
